---
title: DSR Branding
timezone: UTC
collections:
  brand:
    title: Brand
    output: true
    permalink: brand
  posts:
    title: Posts
    output: true
  sliders:
    title: Sliders
    output: true
    permalink: sliders
  uploads:
    title: Uploads
    output: false
  work:
    title: Work
    output: true
    permalink: work
defaults:
- scope:
    path: ''
  values:
    layout: default
- scope:
    path: ''
    type: pages
  values:
    menu: menu
- scope:
    path: ''
    type: work
  values:
    permalink: "/work/:title/"
    link: 
    layout: post
    work_images:
    -
    work_testimonials:
- scope:
    path: ''
    type: testimonials
  values:
    permalink: "/testimonials/:title/"
- scope:
    path: ''
    type: sliders
  values:
    permalink: "/sliders/:title/"
    slider_images:
    -
- scope:
    path: ''
    type: brand
  values:
    permalink: "/brand/:title/"
    brand_colours:
    - 
    logo_image: 
email: dan@dsrb.com.au
mobile: 0401 969 669
baseurl: http://dsrb.siteleaf.net/
description: Branding Agency
address-line-1: Level 1 443
address-line-2: Spring Hill QLD 4000
address-line-3: Upper Edward St
google-address: https://goo.gl/maps/R86aAVX13Kt
google-latitude: 
google-longitude: 
permalink: pretty
markdown: redcarpet
highlighter: pygments
exclude:
- gulpfile.js
- package.json
- README*
- node_modules
- ".gitignore"
