---
title: DSR BRANDING
timezone: UTC
collections:
  brand:
    title: Brand
    output: true
    permalink: brand
  posts:
    title: Posts
    output: true
  sliders:
    title: Sliders
    output: true
    permalink: sliders
  testimonials:
    title: Testimonials
    output: true
    permalink: testimonials
  uploads:
    title: Uploads
    output: false
  work:
    title: Work
    output: true
    permalink: work
defaults:
- scope:
    path: ''
  values:
    layout: default
- scope:
    path: ''
    type: work
  values:
    permalink: "/work/:title/"
    link: 
    layout: post
    work_images: 
    -
- scope:
    path: ''
    type: testimonials
  values:
    permalink: "/testimonials/:title/"
- scope:
    path: ''
    type: sliders
  values:
    permalink: "/sliders/:title/"
    slider_images: 
    -
- scope:
    path: ''
    type: brand
  values:
    permalink: "/brand/:title/"
    brand_colours:
    -
    logo_image: 
email: dan@dsrb.com.au
mobile: "+61 418 852 804"
baseurl: http://dsrb.siteleaf.net/
description: Branding Agency
permalink: pretty
markdown: redcarpet
highlighter: pygments
exclude:
- gulpfile.js
- package.json
- README*
- node_modules
- ".gitignore"
